Imeplement discord controlers
ADEPT-Informatique/ADEPT-API pull request #7
Opened 2021-10-06 05:24 UTC by HandsomeRomanian

- Updated the user with discord requirements ( Student number, discord id, name, study program)
- Created study program: get all, create and deletion impact routes.
-

2021-10-10 15:33 UTC, olivierguy93 requested changes

2021-10-10 15:33 UTC, olivierguy93 commented on ADEPT-API.DATABASE/Models/Discord/DiscordStatusLog.cs
> +        public DiscordStatusLog ReversionLog { get; set; }
Pas obligatoire, mais ajouter virtual ici. pour rester consistent

2021-10-10 15:33 UTC, olivierguy93 commented on ADEPT-API.DATABASE/Models/Users/StudyProgram.cs
> +        public string Name { get; set; }
Si le StudyProgram ne sont pas seeder par programmation, ajoute Required pour le Name

2021-10-10 15:33 UTC, olivierguy93 commented on ADEPT-API.LIBRARY/Dto/Users/StudyProgramDto.cs
> +    public class StudyProgramDto
Ajoute [DataContract] sur la class et [DataMember] sur les propriété

2021-10-10 15:33 UTC, olivierguy93 commented on ADEPT-API.LIBRARY/Services/IStudyProgramService.cs
> +    public interface IStudyProgramService
Ajoute les summary à l'interface

2021-10-10 15:33 UTC, olivierguy93 commented on ADEPT-API.LIBRARY/Services/Internals/StudyProgramService.cs
> +    public class StudyProgramService : IStudyProgramService
Toutes les methode de la class devrait être async Task<> et Ajoute Async à la fin de chaque nom de Méthode

2021-10-10 15:33 UTC, olivierguy93 commented on ADEPT-API.LIBRARY/Services/Internals/StudyProgramService.cs
> +            if (program == null)
Change la condition pour _ = program ?? throw error

2021-10-10 15:33 UTC, olivierguy93 commented on ADEPT-API/Controllers/StudyProgramController.cs
> +            return Ok(_studyProgramService.GetAll());
Pour debugging purpose crée une variable response qui va contenir l'information retourner du service et par la suite return response. (Pour toutes les méthode du controlleur)

2021-10-10 15:33 UTC, olivierguy93 commented on ADEPT-API.LIBRARY/Dto/Users/StudyProgramCreateRequestDto.cs
> +        public string Name { get; set; }
Ajoute DataAnotation [Required]

2021-10-10 15:33 UTC, olivierguy93 commented on ADEPT-API.LIBRARY/Dto/Users/StudyProgramCreateRequestDto.cs
> +    public class StudyProgramCreateRequestDto
Ajoute [DataContract] à la class et [DataMember] pour la propriété

2021-10-12 04:40 UTC, mataai commented on ADEPT-API.LIBRARY/Services/IStudyProgramService.cs
> +    public interface IStudyProgramService
?

2021-10-12 04:46 UTC, mataai commented on ADEPT-API.LIBRARY/Services/Internals/StudyProgramService.cs
> +            if (program == null)
plz explain to me la prochaine fois

2021-10-12 09:18 UTC, olivierguy93 commented on ADEPT-API.LIBRARY/Services/IStudyProgramService.cs
> +    public interface IStudyProgramService
Au-dessus de chaque methode de l'interface to dois faire ///  pour faire apparaître les Summary comme ça tu peux décrire se que la méthode fait

2021-10-16 18:51 UTC, closed without merging